### ISSUE TITLE
interrogar_UD: critério 1 = regex

### ISSUE THREAD

**Issue by alvelvis** [alvelvis/ACDC-UD#1]
Que tal mudar o critério 1 pra expressão regular, que é o critério mais geral, e ir criando os próximos critérios a partir daí? (o critério do root#nsubj vira o critério 2)

**Comment by LRocha7** [comment]
o único problema (que não é problema) de expressão regular é que precisa uma expressão grande pra pouca coisa... e quanto mais detalhes, maior fica a expressão... mas é uma ideia valida
